//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OM_dummy1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Query
    {
        public int QueryID { get; set; }
        public string QueryDescription { get; set; }
        public string QueryType { get; set; }
        public int CustomerID { get; set; }
        public int AgentID { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
